<?php

/**
 * @file
 * Hooks for the Customer Management module.
 */

use Drupal\Core\Render\Markup;

/**
 * Implements hook_theme().
 */
function customer_management_theme() {
  return [
    'customers_list' => [
      'variables' => [
        'content' => [],
      ],
      'template' => 'customers_list',
    ],
    'create_customer' => [
      'render element' => 'form',
      'template' => 'create_customer',
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function customer_management_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];
  $site_name = \Drupal::config('system.site')->get('name') ?: 'Site';

  $message['from'] = \Drupal::config('system.site')->get('mail');
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';

  switch ($key) {
    case 'customer_created':
      $message['subject'] = t('Your customer credentials for @site', ['@site' => $site_name], $options);
      $message['body'][] = Markup::create($params['message']);
      break;

    case 'credentials_resent':
      $message['subject'] = t('Your customer credentials for @site', ['@site' => $site_name], $options);
      $message['body'][] = Markup::create($params['message']);
      break;

    case 'hashed_key_reset':
      $message['subject'] = t('Your customer hashed key has been reset for @site', ['@site' => $site_name], $options);
      $message['body'][] = Markup::create($params['message']);
      break;
  }
}
