<?php

/**
 * Implements hook_mail().
 */
function zcs_user_management_mail($key, &$message, $params) {
    $email_from = \Drupal::config('system.site')->get('mail');
    switch ($key) {
        case 'user_invite':
          $message['from'] = \Drupal::config('system.site')->get('mail');
          $message['subject'] = t('Activate your account');
          $message['body'][] = $params['message'];
          break;
    }
  }


