SELECT 1 AS `id`, 'Jan' AS `name` UNION ALL
SELECT 2, 'Feb' UNION ALL SELECT 3, 'Mar' UNION ALL
SELECT 4, 'Apr' UNION ALL SELECT 5, 'May' UNION ALL
SELECT 6, 'Jun' UNION ALL SELECT 7, 'Jul' UNION ALL
SELECT 8, 'Aug' UNION ALL SELECT 9, 'Sep' UNION ALL
SELECT 10, 'Oct' UNION ALL SELECT 11, 'Nov' UNION ALL
SELECT 12, 'Dec'
ORDER BY `id`
