<?php

/**
 * @file
 * Primary module hooks for zcs Client Management module.
 */

/**
 * Implements hook_theme().
 */
function zcs_client_management_theme($existing, $type, $theme, $path) {
    return [
      'client_view' => [
        'variables' => [
          'image_url' => '',  
          'client_name' => '',
          'contact_name' => '',
          'contact_email' => '',
          'status' => '',
          'description' => '',
          'client_legal_contact' => '',
          'legal_email' => '',
          'address' => '',
          'type' => '',
          'industry' => '',
          'agreement_effective_date' => '',
          'currency' => '',
          'prepayment_amount' => '',
          'prepayment_balance_left' => '',
          'prepayment_balance_used' => '',
          'address_line_1' => '',
          'address_line_2' => '',
          'address_line_3' => '', 
          'country_code' => '',
          'postal_code' => '',
          'agreement_covers' => '',
        ],
        'template' => 'client-view',
      ],
    ];
  }



/**
 * Implements hook_mail().
 */
function zcs_client_management_mail($key, &$message, $params) {
    $email_from = \Drupal::config('system.site')->get('mail');
    switch ($key) {
        case 'client_member_invite':
            $message['from'] = \Drupal::config('system.site')->get('mail');
            $message['subject'] = t('Partner Onboarding - Activate your account');
            $message['body'][] = $params['message'];
            break;
    }
}