<?php

/**
 * @file
 * Primary module hooks for zcs_api_attributes module.
 */

function zcs_api_attributes_theme() {
  return [
    'attributes_page' => [
      'variables' => [
        'content' => null,
      ],
      'template' => 'attributes_page'
    ],
    'change_network_authentication_pricing' => [
      'variables' => [
        'content' => null,
      ],
      'template' => 'change_network_authentication_pricing'
    ],
    'network_authentication_pricing_over_time' => [
      'variables' => [
        'content' => null,
      ],
      'template' => 'network_authentication_pricing_over_time'
    ],
  ];
}