# Schema for the configuration files of the zcs_custom module.
zcs_custom.settings:
  type: config_object
  label: 'zcs_custom settings'
  mapping:
    example:
      type: string
      label: 'Example'
